@startuml

title Empty Diagram - i2c-tx-state.puml

state Idle
state Start
state addr as "Send Address"
state data as "Send Data"
state Restart
state stop

[*] --> Idle
Idle --> Start
Start --> addr
addr --> data
data -left> Restart : Change to read\nafter addr/cmd\nphase
Restart -> addr
data -right> stop : Transaction\ncomplete
stop -up> Idle

@enduml
